# do not push it to your repo!
[database]
connection-type="mysql"
user-name="ves-admin"
password="12345678"
host="localhost"
database-name="ves"
charset="utf8mb4"
parse-time=true
location="Local"
[base-cfg]
nsb-host="39.100.145.91:26657"